Refactor SQL filtering
koopjs/winnow pull request #172
Opened 2020-10-13 22:06 UTC by rgwozdz

This PR:

* put methods into their own files and put under direct unit test
* fixes a bug in the "envelope-intersects" operation.  The old code was checking for an intersection of the feature envelope against the query geometry.  However, research indicates that the Esri envelope-intersects operation should check that an "Envelope of Query Geometry Intersects Envelope of Target Geometry" (see [here](http://resources.esri.com/help/9.3/ArcGISDesktop/ArcObjects/esriGeoDatabase/esriSpatialRelEnum.htm)).
* adds support for the `!=` operator in the hashed OBJECTID comparison.

2020-10-14 14:35 UTC, haoliangyu requested changes

2020-10-14 14:35 UTC, haoliangyu commented on lib/filter-and-transform/filters/contains.js
> +  if (!featureGeometry) return false
Use `_.isEmpty` because the falsy value has defaulted to `{}`.

2020-10-14 14:35 UTC, haoliangyu commented on lib/filter-and-transform/filters/intersects.js
> +  if (!featureGeometry) return false
Use `_.isEmpty`

2020-10-14 14:35 UTC, haoliangyu commented on lib/filter-and-transform/filters/within.js
> +  if (!featureGeometry) return false
Use `_.isEmpty`

2020-10-14 14:35 UTC, haoliangyu commented on test/unit/filter-and-transform/filters/constains.spec.js
> +  const result = contains({}, {})
Probably adding tests for `contains(null, {})` and `contains({}, null)` since you are validating the two parameters separately.

2020-10-15 13:10 UTC, rgwozdz commented
@haoliangyu - requested changes were made in e76946e.

2020-10-15 14:49 UTC, haoliangyu approved these changes

2020-10-15 14:51 UTC, merged